# Generated by Django 3.1 on 2020-09-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=80)),
                ('data_publcacao', models.DateField(default='03/09/2020')),
                ('opcao1', models.CharField(max_length=30)),
                ('opcao2', models.CharField(max_length=30)),
                ('opcao3', models.CharField(max_length=30)),
                ('opcao4', models.CharField(max_length=30)),
                ('tipo_input', models.CharField(max_length=8)),
            ],
        ),
    ]
