# Generated by Django 3.1 on 2020-09-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquete',
            old_name='data_publcacao',
            new_name='data_publicacao',
        ),
    ]
