# Generated by Django 3.1 on 2020-10-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_auto_20200903_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('materia', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Enquete',
        ),
    ]
