# Generated by Django 3.1 on 2020-10-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0006_curso_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(related_name='cursos', to='enquetes.Curso'),
        ),
    ]
