# Generated by Django 3.1 on 2020-10-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0007_auto_20201018_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(related_name='curso', to='enquetes.Curso'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_hora_postagem',
            field=models.DateTimeField(),
        ),
    ]
