# Generated by Django 3.1 on 2020-10-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0009_auto_20201018_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_hora_postagem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
