# Generated by Django 3.1 on 2020-10-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0010_auto_20201018_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='data_hora_postagem',
        ),
    ]
