# Generated by Django 3.1 on 2020-10-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0011_remove_postagem_data_hora_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(to='enquetes.Curso'),
        ),
    ]
